### ISSUE TITLE
http.js: path.resolve not working

### ISSUE THREAD

**Issue by polenz** [istr/smsmtp#1]
I can't see the incoming Email via HTTP.
When I point my browser to ```localhost:3000```, I see ```no mail for: C:\```

I could find the failure in the code. The problem is ```path.resolve``` in line 87 in the http.js. 
When I delete this line, everything works fine.

It is possible to get a fast fix version for that?

Thanks,
kristin

**Comment by istr** [comment]
Hello Kristin,
feel free to fork, remove the line and create a pull request.
I will merge it asap.
Thanks.

**Comment by polenz** [comment]
Hello Ingo,
I created the pull request to solve this issue. 
It would be nice to get a new version after Easter.
Thanks
kristin

**Comment by istr** [comment]
Hello Kristin,
thank you. :-)
Happy Easter.

**Comment by polenz** [comment]
Thanks for merging it.
It would be great to get a new patch version that we can use the fix.
